sudo: required
language: node_js
node_js:
  - 15

services:
  - docker

before_install:
  - docker build -t sidnix/react -f ./client/Dockerfile.dev ./client

script:
  - docker run sidnix/react npm test -- --watchAll=false

after_success:
  - docker build -t sidnix/multi-client ./client
  - docker build -t sidnix/multi-nginx ./nginx
  - docker build -t sidnix/multi-server ./server
  - docker build -t sidnix/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sidnix/multi-client
  - docker push sidnix/multi-nginx
  - docker push sidnix/multi-server
  - docker push sidnix/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-074823772394
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
